server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:  file:///C:/Users/PETERGreaves/Documents/sento-dev/configurations/rateableitems-service, file:///C:/Users/PETERGreaves/Documents/sento-dev/configurations/organisations-service